DROP TABLE IF EXISTS evaluation_release_gates;
DROP TABLE IF EXISTS evaluation_campaigns;
DROP TABLE IF EXISTS evaluation_cases;
DROP TABLE IF EXISTS evaluation_dataset_versions;
DROP TABLE IF EXISTS evaluation_datasets;
DROP TABLE IF EXISTS evaluation_findings;
DROP TABLE IF EXISTS evaluation_results;
DROP TABLE IF EXISTS evaluation_jobs;
DROP TABLE IF EXISTS run_snapshots;
DROP TABLE IF EXISTS otel_flush_receipts;
DROP TABLE IF EXISTS run_spans;
DROP TABLE IF EXISTS run_evaluation_policy_manifest;
DROP TABLE IF EXISTS agent_evaluation_policy_assignments;
DROP TABLE IF EXISTS agent_evaluation_profiles;
DROP TABLE IF EXISTS run_participants;

ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_previous_run_fk;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_capture_status_check;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_evaluation_eligibility_check;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_boundary_confidence_check;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_boundary_source_check;
ALTER TABLE runs DROP COLUMN IF EXISTS dropped_trace_count;
ALTER TABLE runs DROP COLUMN IF EXISTS reevaluation_agent_ids;
ALTER TABLE runs DROP COLUMN IF EXISTS evaluation_eligibility;
ALTER TABLE runs DROP COLUMN IF EXISTS last_evidence_at;
ALTER TABLE runs DROP COLUMN IF EXISTS previous_run_id;
ALTER TABLE runs DROP COLUMN IF EXISTS expected_flush_id;
ALTER TABLE runs DROP COLUMN IF EXISTS capture_deadline;
ALTER TABLE runs DROP COLUMN IF EXISTS capture_status;
ALTER TABLE runs DROP COLUMN IF EXISTS finalized_at;
ALTER TABLE runs DROP COLUMN IF EXISTS boundary_confidence;
ALTER TABLE runs DROP COLUMN IF EXISTS boundary_source;

DROP INDEX IF EXISTS run_events_workspace_run_agent_idx;
DROP INDEX IF EXISTS traces_workspace_run_agent_idx;
DROP INDEX IF EXISTS traces_workspace_environment_agent_created_idx;
ALTER TABLE traces DROP CONSTRAINT IF EXISTS traces_agent_fk;
ALTER TABLE traces DROP COLUMN IF EXISTS late_evidence;
ALTER TABLE traces DROP COLUMN IF EXISTS agent_id;
ALTER TABLE run_events DROP CONSTRAINT IF EXISTS run_events_agent_fk;
ALTER TABLE run_events DROP COLUMN IF EXISTS agent_id;
