import { createOpenAPI } from 'fumadocs-openapi/server';
import { createAPIPage } from 'fumadocs-openapi/ui';
import { resolve } from 'node:path';

// Single source of truth: docs/openapi.yaml is generated by `cargo run -p
// tl-codegen` from the Rust types. The OpenAPI generator script and the
// runtime page renderer both read from this server, so the schemaId
// ("trustloopguard") matches the document="..." prop in generated MDX.
export const openapiServer = createOpenAPI({
  input: () => ({
    trustloopguard: resolve(process.cwd(), '../../docs/openapi.yaml'),
  }),
});

export const APIPage = createAPIPage(openapiServer);
