export const PROCUREMENT_DEMO_COPY = {
  en: {
    examples: [
      {
        label: 'Approved chairs · allow',
        prompt: 'Order the approved office chairs for $2,400.',
      },
      {
        label: 'Laptops · review',
        prompt: 'Order the approved developer laptops for $42,000.',
      },
      {
        label: 'Unapproved vendor · block',
        prompt: 'Order the office supplies from the unapproved vendor.',
      },
      {
        label: 'Gift cards · block',
        prompt: 'Order the employee gift cards from the approved vendor.',
      },
    ],
    buyerWorkspace: 'Buyer workspace',
    agentTitle: 'Procurement agent',
    liveOpenAi: 'Live OpenAI',
    safetyLabel: 'Synthetic demo data notice',
    safetyNote: 'Synthetic demo only · no real purchasing',
    dataNotice:
      'Demo catalog only. Do not enter confidential procurement, supplier, or commercial information.',
    agentLabel: 'Procurement agent',
    buyerLabel: 'Buyer',
    greeting:
      'I can search a fixed demo catalog and propose one purchase order. TrustLoopGuard checks the exact supplier, category, and review tier before anything is submitted.',
    working: 'OpenAI is checking the catalog and proposing tools…',
    errorTitle: 'Purchase order stopped safely',
    fallbackError: 'The live procurement workflow failed safely.',
    limitError: 'Demo limit reached. Try again later.',
    examplesLabel: 'Example procurement requests',
    buyerRequest: 'Buyer request',
    runningButton: 'Running live agent',
    runButton: 'Run secure procurement agent',
    controlsEyebrow: 'Rust-enforced controls',
    controlsTitle: 'TrustLoopGuard policy stack',
    workflow: [
      {
        title: 'OpenAI agent',
        idle: 'Searches the catalog and chooses whether to propose submit_purchase_order.',
        complete: 'OpenAI searched the catalog and chose whether to propose a purchase action.',
      },
      {
        title: 'Catalog evidence',
        idle: 'Resolves a quote to server-owned supplier and price facts.',
        complete: 'Resolved the request against server-owned supplier and pricing facts.',
      },
      {
        title: 'TrustLoopGuard',
        idle: 'Evaluates the exact action against the enabled Rust policy profile.',
        permit: 'The proposed purchase action passed the enabled Rust policies.',
        deny: 'TrustLoopGuard blocked the proposed purchase action.',
        review: 'TrustLoopGuard held the proposed purchase action for human approval.',
        noAction: 'The agent did not propose a purchase action for TrustLoopGuard to evaluate.',
      },
      {
        title: 'Procurement system',
        idle: 'Receives one simulated purchase order only after TrustLoopGuard permits it.',
        submitted: 'The simulated procurement system received the permitted purchase order.',
        review: 'Not called. The purchase order is waiting for human approval.',
        blocked: 'Not called. TrustLoopGuard stopped the proposed action.',
        noAction: 'Not called. The agent did not propose a purchase order.',
      },
    ],
    policiesChecked: 'Policies checked',
    loading: 'Loading',
    unavailable: 'Unavailable',
    active: 'active',
    inPack: 'in pack',
    loadingRegistry: 'Loading the policy registry…',
    inventoryUnavailable: 'Policy inventory unavailable. Purchase actions still fail closed.',
    previewLead: 'Policy pack preview.',
    previewDetail:
      'The Rust registry is unavailable, so these are the action policies installed by the demo setup. Runtime checks still fail closed.',
    noPolicies: 'No enabled procurement demo policies were found. Run the demo setup command.',
    policyWorkspace: 'Workspace holding these policies',
    previewWorkspace: 'Configured demo workspace',
    serverDefaultWorkspace: 'Rust server default',
    matchedThisAction: 'Matched this action',
    activeInRust: 'Active in Rust',
    policyPackPreview: 'Policy pack preview',
    action: 'Action',
    check: 'check',
    policyDescriptions: {
      'procurement-approved-suppliers':
        'Blocks purchase orders for suppliers outside the approved vendor list.',
      'procurement-high-value-review':
        'Holds high-value purchase orders for an owner or administrator to approve.',
      'procurement-restricted-categories':
        'Blocks gift cards and other categories that procurement does not permit.',
    },
    ready: 'Ready',
    checking: 'Checking',
    permitted: 'Permitted',
    heldForReview: 'Held for review',
    blocked: 'Blocked',
    noAction: 'No action',
    authorizationProof: 'Authorization proof',
    waitingForAction: 'Waiting for a proposed action',
    effect: 'Effect',
    notChecked: 'Not checked',
    matchedPolicy: 'Matched policy',
    none: 'None',
    latency: 'Latency',
    approval: 'Approval',
    notRequired: 'Not required',
    providerOutcome: 'Provider outcome',
    noPurchaseOrder: 'No purchase order created',
    status: 'Status',
    notCalled: 'Not called',
    supplier: 'Supplier',
    total: 'Total',
    submitted: 'Submitted',
  },
  vi: {
    examples: [
      {
        label: 'Ghế đã duyệt · cho phép',
        prompt: 'Đặt mua ghế văn phòng đã được phê duyệt với giá 2.400 USD.',
      },
      {
        label: 'Laptop · cần duyệt',
        prompt: 'Đặt mua laptop dành cho lập trình viên đã được phê duyệt với giá 42.000 USD.',
      },
      {
        label: 'Nhà cung cấp chưa duyệt · chặn',
        prompt: 'Đặt mua vật tư văn phòng từ nhà cung cấp chưa được phê duyệt.',
      },
      {
        label: 'Thẻ quà tặng · chặn',
        prompt: 'Đặt mua thẻ quà tặng cho nhân viên từ nhà cung cấp đã được phê duyệt.',
      },
    ],
    buyerWorkspace: 'Không gian người mua',
    agentTitle: 'Tác nhân mua sắm',
    liveOpenAi: 'OpenAI trực tiếp',
    safetyLabel: 'Thông báo dữ liệu demo tổng hợp',
    safetyNote: 'Chỉ demo tổng hợp · không mua hàng thật',
    dataNotice:
      'Chỉ sử dụng danh mục demo. Không nhập thông tin mua sắm, nhà cung cấp hoặc thương mại mật.',
    agentLabel: 'Tác nhân mua sắm',
    buyerLabel: 'Người mua',
    greeting:
      'Tôi có thể tìm trong danh mục demo cố định và đề xuất một đơn mua hàng. TrustLoopGuard kiểm tra chính xác nhà cung cấp, danh mục và mức xét duyệt trước khi gửi đơn.',
    working: 'OpenAI đang kiểm tra danh mục và đề xuất công cụ…',
    errorTitle: 'Đơn mua hàng đã được dừng an toàn',
    fallbackError: 'Quy trình mua sắm trực tiếp đã dừng an toàn.',
    limitError: 'Đã đạt giới hạn demo. Vui lòng thử lại sau.',
    examplesLabel: 'Yêu cầu mua sắm mẫu',
    buyerRequest: 'Yêu cầu của người mua',
    runningButton: 'Đang chạy tác nhân trực tiếp',
    runButton: 'Chạy tác nhân mua sắm an toàn',
    controlsEyebrow: 'Kiểm soát thực thi bằng Rust',
    controlsTitle: 'Bộ chính sách TrustLoopGuard',
    workflow: [
      {
        title: 'Tác nhân OpenAI',
        idle: 'Tìm trong danh mục và quyết định có đề xuất submit_purchase_order hay không.',
        complete: 'OpenAI đã tìm trong danh mục và quyết định có đề xuất hành động mua hàng hay không.',
      },
      {
        title: 'Bằng chứng danh mục',
        idle: 'Đối chiếu báo giá với dữ liệu nhà cung cấp và giá do máy chủ quản lý.',
        complete: 'Đã đối chiếu yêu cầu với dữ liệu nhà cung cấp và giá do máy chủ quản lý.',
      },
      {
        title: 'TrustLoopGuard',
        idle: 'Đánh giá chính xác hành động theo hồ sơ chính sách Rust đang bật.',
        permit: 'Hành động mua hàng đề xuất đã vượt qua các chính sách Rust đang bật.',
        deny: 'TrustLoopGuard đã chặn hành động mua hàng đề xuất.',
        review: 'TrustLoopGuard đã giữ hành động mua hàng để con người phê duyệt.',
        noAction: 'Tác nhân không đề xuất hành động mua hàng để TrustLoopGuard đánh giá.',
      },
      {
        title: 'Hệ thống mua sắm',
        idle: 'Chỉ nhận một đơn mua hàng mô phỏng sau khi TrustLoopGuard cho phép.',
        submitted: 'Hệ thống mua sắm mô phỏng đã nhận đơn mua hàng được cho phép.',
        review: 'Chưa được gọi. Đơn mua hàng đang chờ con người phê duyệt.',
        blocked: 'Chưa được gọi. TrustLoopGuard đã dừng hành động đề xuất.',
        noAction: 'Chưa được gọi. Tác nhân không đề xuất đơn mua hàng.',
      },
    ],
    policiesChecked: 'Chính sách đã kiểm tra',
    loading: 'Đang tải',
    unavailable: 'Không khả dụng',
    active: 'đang bật',
    inPack: 'trong bộ',
    loadingRegistry: 'Đang tải sổ đăng ký chính sách…',
    inventoryUnavailable:
      'Không thể tải danh sách chính sách. Hành động mua hàng vẫn được dừng an toàn khi kiểm tra lỗi.',
    previewLead: 'Bản xem trước bộ chính sách.',
    previewDetail:
      'Sổ đăng ký Rust không khả dụng, nên đây là các chính sách hành động mà thiết lập demo sẽ cài đặt. Kiểm tra lúc chạy vẫn dừng an toàn khi có lỗi.',
    noPolicies:
      'Không tìm thấy chính sách demo mua sắm nào đang bật. Hãy chạy lệnh thiết lập demo.',
    policyWorkspace: 'Không gian làm việc chứa các chính sách này',
    previewWorkspace: 'Không gian làm việc được cấu hình cho demo',
    serverDefaultWorkspace: 'Không gian mặc định của máy chủ Rust',
    matchedThisAction: 'Khớp với hành động này',
    activeInRust: 'Đang bật trong Rust',
    policyPackPreview: 'Xem trước bộ chính sách',
    action: 'Hành động',
    check: 'kiểm tra',
    policyDescriptions: {
      'procurement-approved-suppliers':
        'Chặn đơn mua hàng từ nhà cung cấp ngoài danh sách đã được phê duyệt.',
      'procurement-high-value-review':
        'Giữ đơn mua hàng giá trị cao để chủ sở hữu hoặc quản trị viên phê duyệt.',
      'procurement-restricted-categories':
        'Chặn thẻ quà tặng và các danh mục khác không được bộ phận mua sắm cho phép.',
    },
    ready: 'Sẵn sàng',
    checking: 'Đang kiểm tra',
    permitted: 'Đã cho phép',
    heldForReview: 'Đang chờ phê duyệt',
    blocked: 'Đã chặn',
    noAction: 'Không có hành động',
    authorizationProof: 'Bằng chứng ủy quyền',
    waitingForAction: 'Đang chờ hành động đề xuất',
    effect: 'Hiệu lực',
    notChecked: 'Chưa kiểm tra',
    matchedPolicy: 'Chính sách khớp',
    none: 'Không có',
    latency: 'Độ trễ',
    approval: 'Phê duyệt',
    notRequired: 'Không cần',
    providerOutcome: 'Kết quả hệ thống',
    noPurchaseOrder: 'Chưa tạo đơn mua hàng',
    status: 'Trạng thái',
    notCalled: 'Chưa được gọi',
    supplier: 'Nhà cung cấp',
    total: 'Tổng tiền',
    submitted: 'Đã gửi',
  },
} as const;
