# Generated by `cargo run -p tl-codegen` from docs/openapi.yaml.
# Do not hand-edit.

# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class ApiErrorCode(Enum):
    invalid = 'invalid'
    unauthorized = 'unauthorized'
    forbidden = 'forbidden'
    not_found = 'not_found'
    gone = 'gone'
    unprocessable = 'unprocessable'
    rate_limited = 'rate_limited'
    internal = 'internal'
    unavailable = 'unavailable'


class Channel(Enum):
    voice = 'voice'
    chat = 'chat'
    email = 'email'


class CheckRequest(BaseModel):
    agent_id: str
    channel: Channel
    context: Any | None = None
    domain: str | None = Field(
        None,
        description='Optional domain selector for the dispatcher. Defaults to\n`customer_support` server-side when absent. Reserved for future\n`voice_agent` / `coding_agent` handlers.',
    )
    input: str
    policies: list[str] | None = None
    proposed_output: str
    trace_id: str | None = None


class Severity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class TriggeredPolicy(BaseModel):
    id: str
    reason: str
    severity: Severity


class Verdict(Enum):
    allow = 'allow'
    block = 'block'
    rewrite = 'rewrite'
    escalate = 'escalate'


class TierResult(RootModel[Any]):
    root: Any


class ApiError(BaseModel):
    code: ApiErrorCode
    details: Any | None = Field(
        None,
        description='Opaque structured details (e.g. validation field path).\nDefaults to `null`; servers may add fields without breaking SDKs.',
    )
    message: str
    retriable: bool = Field(
        ...,
        description='Whether the caller may retry the same request without modification.\nSDKs honor `Retry-After` when present in addition to this flag.',
    )


class Decision(BaseModel):
    latency_ms: conint(ge=0)
    reason: str
    safe_output: str | None = None
    tier_results: list[TierResult] | None = Field(
        None,
        description='Per-tier breakdown produced by the parallel-cancel orchestrator.\nEmpty for callers that only ran the synchronous `Engine::check`\npath; populated when `Engine::check_async` is used.',
    )
    trace_id: str
    triggered_policies: list[TriggeredPolicy]
    verdict: Verdict
