# Generated by `cargo run -p tl-codegen` from docs/openapi.yaml.
# Do not hand-edit.

# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class AgentAuthority(BaseModel):
    can_promise: list[str] | None = None
    cannot_promise: list[str] | None = None


class AgentScope(BaseModel):
    in_scope: list[str] | None = None
    out_of_scope: list[str] | None = None


class AgentTone(BaseModel):
    forbidden: list[str] | None = None
    target: str


class AnalyticsChartType(Enum):
    big_number = 'big_number'
    bar = 'bar'
    line = 'line'
    area = 'area'
    donut = 'donut'
    table = 'table'


class AnalyticsDimension(Enum):
    agent_id = 'agent_id'
    environment = 'environment'
    run_kind = 'run_kind'
    run_status = 'run_status'
    decision = 'decision'
    policy_id = 'policy_id'
    workflow_step = 'workflow_step'
    review_outcome = 'review_outcome'
    external_id = 'external_id'


class AnalyticsFacet(BaseModel):
    dimension: AnalyticsDimension
    label: str
    values: list[str]


class AnalyticsFilter(BaseModel):
    dimension: AnalyticsDimension
    values: list[str]


class AnalyticsMetric(Enum):
    trace_count = 'trace_count'
    allow_count = 'allow_count'
    block_count = 'block_count'
    rewrite_count = 'rewrite_count'
    escalate_count = 'escalate_count'
    intervention_rate = 'intervention_rate'
    p95_latency_ms = 'p95_latency_ms'
    human_review_count = 'human_review_count'
    human_intervention_rate = 'human_intervention_rate'
    false_positive_rate = 'false_positive_rate'


class AnalyticsQueryPoint(BaseModel):
    label: str
    value: float


class AnalyticsQueryRequest(BaseModel):
    filters: list[AnalyticsFilter] | None = None
    group_by: AnalyticsDimension | None = None
    limit: conint(ge=0) | None = None
    metric: AnalyticsMetric


class AnalyticsQueryResponse(BaseModel):
    group_by: AnalyticsDimension | None = None
    metric: AnalyticsMetric
    points: list[AnalyticsQueryPoint]
    total: float


class AnalyticsWidgetLayout(BaseModel):
    h: conint(ge=0)
    w: conint(ge=0)
    x: conint(ge=0)
    y: conint(ge=0)


class ApiErrorCode(Enum):
    invalid = 'invalid'
    unauthorized = 'unauthorized'
    forbidden = 'forbidden'
    not_found = 'not_found'
    gone = 'gone'
    unprocessable = 'unprocessable'
    rate_limited = 'rate_limited'
    internal = 'internal'
    unavailable = 'unavailable'


class ApiKeyBatchRevokeRequest(BaseModel):
    ids: list[str]


class ApprovalRequirement(BaseModel):
    approver_roles: list[str] | None = None
    expires_at: str | None = None
    reason: str
    required: bool


class ApprovalRule(BaseModel):
    approver_roles: list[str] | None = None
    reason: str | None = None
    required: bool


class AuthRequest(BaseModel):
    password: str = Field(
        ..., description="SHA-256-hex of the user's plaintext password."
    )
    username: str = Field(
        ...,
        description='Account identifier. Stored as-given, matched case-insensitively.',
    )


class AuthResponse(BaseModel):
    jwt: str | None = Field(
        None,
        description='Signed bearer token (HS256) issued by `tl-server` on successful\nsignup or login. The web dashboard stashes this in the\nNextAuth session and forwards it on every Rust API call as\n`Authorization: Bearer <jwt>`. Absent when the server runs\nwithout `TL_JWT_SECRET` configured (memory-only dev mode).',
    )
    user_id: str
    username: str


class BudgetAlertFiring(BaseModel):
    cap_minor: int
    config_id: str
    currency: str
    fired_at: str = Field(..., description='RFC 3339 timestamp.')
    id: str
    payload: Any = Field(
        ..., description='The exact JSON body delivered to the webhook.'
    )
    principal_id: str
    spent_minor: int
    window_start: str = Field(
        ..., description='RFC 3339 window boundary the dedup key is anchored to.'
    )
    workspace_id: str


class BudgetAlertFiringListResponse(BaseModel):
    firings: list[BudgetAlertFiring]


class BudgetAlertThresholdType(Enum):
    percent = 'percent'
    absolute = 'absolute'


class BudgetAlertWindow(Enum):
    day = 'day'
    week = 'week'
    month = 'month'


class ChangePasswordRequest(BaseModel):
    current_password: str = Field(
        ..., description="SHA-256-hex of the user's current password."
    )
    new_password: str = Field(
        ..., description='SHA-256-hex of the new password to store.'
    )
    username: str


class Channel(Enum):
    voice = 'voice'
    chat = 'chat'
    email = 'email'


class ComparedAttackStatus(Enum):
    fixed = 'fixed'
    still_vulnerable = 'still_vulnerable'
    regressed = 'regressed'
    unchanged = 'unchanged'


class Confidentiality(Enum):
    public = 'public'
    private = 'private'
    secret = 'secret'
    identity = 'identity'
    unknown = 'unknown'


class CounterpartyRef(BaseModel):
    country: str | None = None
    display_name: str | None = None
    id: str
    kind: str
    metadata: Any | None = None


class CreateApiKeyRequest(BaseModel):
    environment_id: str | None = None
    name: str
    principal_id: str | None = Field(
        None,
        description='Optional principal to bind the key to (free-form, e.g.\n`user:daniel`). Requests authenticated with the key resolve to\nthis principal for mandates, budgets, and the audit trail.',
    )


class CreateBudgetAlertConfigRequest(BaseModel):
    enabled: bool | None = Field(None, description='Defaults to `true`.')
    name: str
    principal_id: str | None = None
    threshold_type: BudgetAlertThresholdType
    threshold_value: int
    webhook_url: str | None = None
    window: BudgetAlertWindow


class CreateFinancialMandateRequest(BaseModel):
    expires_at: str | None = None
    id: str | None = None
    metadata: Any | None = None
    principal_id: str
    scope: Any | None = None
    starts_at: str | None = None
    version: int | None = None


class CreateGatewayRouteRequest(BaseModel):
    agent_id: str
    display_name: str
    enforcement_profile_id: str
    id: str | None = None
    provider_connection_id: str


class Kind(Enum):
    added = 'added'


class Kind1(Enum):
    invited = 'invited'


class CreateReportRequest(BaseModel):
    compare_job_id: str | None = Field(
        None, description='Optional second run of the same agent to compare against.'
    )
    job_id: str = Field(..., description='The completed job to report on.')
    ttl_days: conint(ge=0) | None = Field(
        None,
        description='Days until the link expires. Clamped server-side; defaults to 30.',
    )


class CreateWorkspaceEnvironmentRequest(BaseModel):
    description: str | None = None
    is_default: bool | None = None
    name: str
    slug: str


class CreateWorkspaceRequest(BaseModel):
    name: str


class DashboardApiKey(BaseModel):
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    created_by: str | None = None
    environment: str
    environment_id: str
    id: str
    last_used_at: str | None = Field(None, description='RFC 3339 timestamp.')
    name: str
    prefix: str
    principal_id: str | None = Field(
        None,
        description='Principal this key is bound to; requests made with the key are\nattributed to this principal. `None` = workspace-level key.',
    )
    status: str


class DashboardKnowledgeSourceKind(Enum):
    url = 'url'
    file = 'file'
    note = 'note'


class DataHandlingMode(Enum):
    raw_allowed = 'raw_allowed'
    redacted_only = 'redacted_only'
    no_body_retention = 'no_body_retention'
    private_deployment = 'private_deployment'


class EnforcementMode(Enum):
    off = 'off'
    shadow = 'shadow'
    enforce = 'enforce'


class EnvironmentCheckerModes(BaseModel):
    approval_checker_mode: EnforcementMode | None = None
    flow_checker_mode: EnforcementMode | None = None
    memory_checker_mode: EnforcementMode | None = None
    param_checker_mode: EnforcementMode | None = None
    updated_at: str | None = Field(None, description='RFC 3339 timestamp.')


class EventKind(Enum):
    output_proposed = 'output.proposed'
    tool_call_proposed = 'tool.call.proposed'
    memory_write_proposed = 'memory.write.proposed'
    memory_retrieval_used_for_action = 'memory.retrieval.used_for_action'
    file_action_proposed = 'file.action.proposed'
    shell_action_proposed = 'shell.action.proposed'
    network_request_proposed = 'network.request.proposed'
    browser_action_proposed = 'browser.action.proposed'
    database_mutation_proposed = 'database.mutation.proposed'
    api_mutation_proposed = 'api.mutation.proposed'
    external_message_proposed = 'external_message.proposed'


class EvidenceRef(BaseModel):
    kind: str
    metadata: Any | None = None
    observed_at: str | None = None
    source: str
    source_id: str


class FailMode(Enum):
    open = 'open'
    closed = 'closed'


class FinancialActionDecision(Enum):
    allow = 'allow'
    hold = 'hold'
    block = 'block'
    escalate = 'escalate'


class FinancialActionKind(Enum):
    payment = 'payment'
    refund = 'refund'
    payout = 'payout'
    invoice_approval = 'invoice_approval'
    purchase = 'purchase'
    treasury_transfer = 'treasury_transfer'
    consent = 'consent'
    other = 'other'


class FinancialActionOutcomeStatus(Enum):
    pending = 'pending'
    succeeded = 'succeeded'
    failed = 'failed'
    canceled = 'canceled'
    reversed = 'reversed'
    recovery_started = 'recovery_started'
    recovered = 'recovered'
    disputed = 'disputed'
    loss_recorded = 'loss_recorded'
    unknown = 'unknown'


class FinancialActionPrecondition(Enum):
    order_exists = 'order_exists'
    payment_captured = 'payment_captured'
    refund_window_open = 'refund_window_open'
    amount_lte_refundable_balance = 'amount_lte_refundable_balance'
    destination_is_original_payment_method = 'destination_is_original_payment_method'
    no_duplicate_refund = 'no_duplicate_refund'
    invoice_matches_po = 'invoice_matches_po'
    vendor_approved = 'vendor_approved'
    mandate_valid = 'mandate_valid'
    custom = 'custom'


class FinancialActionStatus(Enum):
    proposed = 'proposed'
    authorized = 'authorized'
    held = 'held'
    executed = 'executed'
    denied = 'denied'
    failed = 'failed'
    reversed = 'reversed'
    expired = 'expired'


class FinancialApprovalRequestStatus(Enum):
    pending = 'pending'
    approved = 'approved'
    denied = 'denied'
    expired = 'expired'
    canceled = 'canceled'


class FinancialDecisionRiskCode(Enum):
    amount_above_auto_approve_threshold = 'amount_above_auto_approve_threshold'
    amount_over_per_transaction_cap = 'amount_over_per_transaction_cap'
    missing_authorization_scope = 'missing_authorization_scope'
    authorization_scope_invalid = 'authorization_scope_invalid'
    counterparty_denied = 'counterparty_denied'
    counterparty_not_allowed = 'counterparty_not_allowed'
    new_counterparty = 'new_counterparty'
    missing_evidence = 'missing_evidence'
    failed_evidence = 'failed_evidence'
    daily_cap_exceeded = 'daily_cap_exceeded'
    weekly_cap_exceeded = 'weekly_cap_exceeded'
    monthly_cap_exceeded = 'monthly_cap_exceeded'
    provider_not_executed = 'provider_not_executed'
    provider_failed = 'provider_failed'
    unknown = 'unknown'


class FinancialEligibilityStatus(Enum):
    passed = 'passed'
    failed = 'failed'
    missing = 'missing'


class FinancialEvidenceProof(BaseModel):
    evidence_source_id: str | None = None
    precondition: FinancialActionPrecondition
    reason: str | None = None
    status: FinancialEligibilityStatus


class FinancialExecutionProofStatus(Enum):
    not_started = 'not_started'
    not_required = 'not_required'
    executed = 'executed'
    failed = 'failed'
    receipt_missing = 'receipt_missing'


class FinancialMandateStatus(Enum):
    active = 'active'
    revoked = 'revoked'
    expired = 'expired'


class FinancialRail(Enum):
    payment_http = 'payment_http'
    card = 'card'
    ach = 'ach'
    wire = 'wire'
    internal = 'internal'
    other = 'other'


class FinancialReceipt(BaseModel):
    action_id: str
    created_at: str
    id: str
    ledger_event_ids: list[str] | None = None
    proof: Any | None = None
    trace_id: str | None = None


class GatewayCredentialStatus(Enum):
    configured = 'configured'
    missing = 'missing'


class GatewayInputAction(Enum):
    allow = 'allow'
    block = 'block'
    redact = 'redact'


class GatewayOutputAction(Enum):
    allow = 'allow'
    block = 'block'
    rewrite = 'rewrite'
    escalate = 'escalate'


class GatewayProviderKind(Enum):
    openai_compatible = 'openai_compatible'
    anthropic = 'anthropic'
    payment_http = 'payment_http'


class GatewayRoute(BaseModel):
    agent_id: str
    created_at: str
    display_name: str
    enforcement_profile_id: str
    id: str
    provider_connection_id: str
    updated_at: str


class GatewayRouteListResponse(BaseModel):
    gateway_routes: list[GatewayRoute]


class HardenCandidateOperation(Enum):
    create = 'create'
    tighten = 'tighten'


class HardenRejectionReason(Enum):
    no_target_reply = 'no_target_reply'
    synthesis_invalid = 'synthesis_invalid'
    missed_landed = 'missed_landed'
    missed_variant = 'missed_variant'
    false_blocked_control = 'false_blocked_control'
    semantic_judge_unavailable = 'semantic_judge_unavailable'
    unreachable_substrate = 'unreachable_substrate'


class HardenRequest(BaseModel):
    persist: bool | None = Field(
        None,
        description='`false` (default) previews candidates without persisting; `true` upserts\nthe survivors `enabled = false`.',
    )


class HumanReviewAnalyticsSummary(BaseModel):
    automated_intervention_count: int
    false_positive_rate: float
    human_intervention_count: int
    human_intervention_rate: float
    human_review_count: int
    trace_count: int


class HumanReviewGroupRow(BaseModel):
    group: str
    human_intervention_count: int
    human_review_count: int


class HumanReviewOutcome(Enum):
    accepted = 'accepted'
    corrected = 'corrected'
    rejected = 'rejected'
    false_positive = 'false_positive'
    missed_issue = 'missed_issue'
    ignored = 'ignored'


class HumanReviewOutcomeCounts(BaseModel):
    accepted_count: int
    corrected_count: int
    false_positive_count: int
    ignored_count: int
    missed_issue_count: int
    rejected_count: int


class HumanReviewPolicyRow(BaseModel):
    corrected_count: int
    escalation_count: int
    false_positive_count: int
    policy_id: str


class HumanReviewReasonRow(BaseModel):
    count: int
    reason_code: str


class HumanReviewWorkflowStepRow(BaseModel):
    corrected_count: int
    false_positive_count: int
    human_review_count: int
    rejected_count: int
    workflow_step: str


class Integrity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    unknown = 'unknown'


class InviteStatus(Enum):
    pending = 'pending'
    accepted = 'accepted'
    revoked = 'revoked'
    expired = 'expired'


class JobStatus(Enum):
    queued = 'queued'
    running = 'running'
    complete = 'complete'
    error = 'error'
    cancelled = 'cancelled'


class KnowledgeFileInput(BaseModel):
    data_base64: str
    file_name: str
    media_type: str


class KnowledgeFileMetadata(BaseModel):
    byte_size: int
    checksum_sha256: str
    file_name: str
    media_type: str


class KnowledgeSourceFileResponse(BaseModel):
    byte_size: int
    data_base64: str
    file_name: str
    media_type: str


class KnowledgeSourceKind(Enum):
    local = 'local'
    web = 'web'


class KnowledgeSourceStatus(Enum):
    draft = 'draft'
    indexing = 'indexing'
    ready = 'ready'
    failed = 'failed'


class LabelBasis(Enum):
    origin_default = 'origin_default'
    workspace_override = 'workspace_override'
    declared = 'declared'


class LabelBasisSet(BaseModel):
    confidentiality: LabelBasis
    integrity: LabelBasis
    trust: LabelBasis


class LabelPolicyStatus(Enum):
    not_configured = 'not_configured'
    applied = 'applied'
    unavailable = 'unavailable'


class LimitAction(Enum):
    block = 'block'
    escalate = 'escalate'


class LlmPriceSource(Enum):
    workspace = 'workspace'
    default = 'default'


class LlmUsageBucket(BaseModel):
    calls: int
    completion_tokens: int
    cost_minor: int
    key: str
    prompt_tokens: int
    unpriced: bool | None = Field(
        None,
        description='`true` when the model has no effective price entry (workspace or\nbuilt-in) — its `cost_minor` undercounts real spend. Only set on\n`group_by=model` buckets; omitted when priced.',
    )


class LlmUsageBucketsResponse(BaseModel):
    buckets: list[LlmUsageBucket]


class LlmUsageEvent(BaseModel):
    api_key_id: str
    completion_tokens: int
    cost_minor: int = Field(
        ...,
        description='Priced cost in currency minor units. `0` when the model has no\nprice table entry.',
    )
    currency: str
    effective_at: str = Field(..., description='RFC 3339 timestamp.')
    id: str
    metadata: Any
    model: str = Field(
        ...,
        description='Raw model string from the provider response (deployment prefixes\nand all); pricing normalization never rewrites it.',
    )
    principal_id: str = Field(
        ...,
        description='Principal the spend is attributed to. Keys without a bound\nprincipal fall back to the API key id.',
    )
    prompt_tokens: int
    request_id: str = Field(
        ...,
        description='Gateway request id — unique per workspace, makes retried\nmetering writes idempotent.',
    )
    workspace_id: str


class LlmUsageListResponse(BaseModel):
    events: list[LlmUsageEvent]


class LlmUsageResponse(RootModel[LlmUsageListResponse | LlmUsageBucketsResponse]):
    root: LlmUsageListResponse | LlmUsageBucketsResponse = Field(
        ...,
        description='`GET /v1/llm-usage` 200 body: the raw event list, or grouped buckets\nwhen `group_by` is set. Untagged — the two shapes are distinguished\nby their sole field (`events` vs `buckets`).',
    )


class MandateRef(BaseModel):
    id: str
    version: int | None = None


class MoneyAmount(BaseModel):
    amount_minor: int
    currency: str


class OAuthIdentityRequest(BaseModel):
    email: str = Field(
        ...,
        description='Provider-verified or provider-supplied email. Used to link a\nfirst OAuth sign-in to an existing local app user.',
    )
    name: str | None = None
    provider: str = Field(
        ..., description='Provider id from Auth.js, e.g. `google` or `github`.'
    )
    provider_subject: str = Field(
        ..., description='Stable provider account id (`account.providerAccountId`).'
    )


class Origin(Enum):
    user = 'user'
    system = 'system'
    tool = 'tool'
    memory = 'memory'
    file = 'file'
    web = 'web'
    email = 'email'
    api = 'api'
    unknown = 'unknown'


class ParamLimit(BaseModel):
    max: int | None = Field(
        None,
        description='Inclusive maximum. A value greater than this breaches the limit.',
    )
    min: int | None = Field(
        None,
        description='Inclusive minimum. A value less than this breaches the limit.',
    )
    on_breach: LimitAction | None = Field(
        None,
        description='Verdict to recommend when a bound is breached. Defaults to `Block`.',
    )


class ParamRole(Enum):
    authority_bearing = 'authority_bearing'
    content_bearing = 'content_bearing'


class PolicyAction(Enum):
    block = 'block'
    rewrite = 'rewrite'
    escalate = 'escalate'


class PolicyBatchSetEnabledRequest(BaseModel):
    enabled: bool
    ids: list[str]


class PolicyDraftRequest(BaseModel):
    prompt: str


class PolicyFamily(Enum):
    content = 'content'
    flow = 'flow'
    parameter_source = 'parameter_source'
    approval = 'approval'
    memory = 'memory'
    financial = 'financial'
    source_label = 'source_label'


class PolicyMatchType(Enum):
    literal = 'literal'
    regex = 'regex'
    semantic = 'semantic'


class PolicySetEnabledRequest(BaseModel):
    enabled: bool


class PolicyValidationIssue(BaseModel):
    message: str
    path: str


class Principal(BaseModel):
    agent_id: str
    environment_id: str
    run_event_id: str | None = None
    run_id: str | None = None
    session_id: str | None = None
    task_id: str | None = None
    user_id: str | None = None
    workspace_id: str


class ProvenanceMap(RootModel[dict[str, list[str]]]):
    root: dict[str, list[str]]


class RecoveryStatus(Enum):
    not_needed = 'not_needed'
    not_available = 'not_available'
    available = 'available'
    started = 'started'
    recovered = 'recovered'
    failed = 'failed'
    manual_required = 'manual_required'


class RedactedEntity(BaseModel):
    count: conint(ge=0)
    entity_type: str
    token: str


class RedactionMode(Enum):
    sdk_local = 'sdk_local'
    customer_service = 'customer_service'
    server = 'server'


class RedactionStatus(Enum):
    not_requested = 'not_requested'
    applied = 'applied'
    failed = 'failed'
    rejected_raw_sensitive_data = 'rejected_raw_sensitive_data'


class RedteamAttackRecord(BaseModel):
    attack: str
    created_at: str = Field(
        ..., description="RFC 3339 timestamp of the parent job's creation."
    )
    goal: str
    job_id: str = Field(..., description='The parent job this attack belongs to.')
    landed: bool
    outcome: str = Field(..., description='`landed` | `blocked` | `clean` | `error`.')
    profile: str
    prompt: str | None = None
    reply: str
    seq: int
    target: str
    trace_id: str | None = None


class RedteamAttackRecordListResponse(BaseModel):
    records: list[RedteamAttackRecord]


class RedteamAttackSurface(Enum):
    chat = 'chat'
    document_workflow = 'document_workflow'


class RedteamComparedAttack(BaseModel):
    attack: str
    baseline_outcome: str = Field(
        ..., description='`landed` | `blocked` | `clean` | `error` on the baseline run.'
    )
    compare_outcome: str | None = Field(
        None,
        description='Same on the compared run; `null` when the attack is absent there.',
    )
    goal: str
    status: ComparedAttackStatus


class RedteamDocumentTemplate(BaseModel):
    data_base64: str
    fields: dict[str, str] | None = None
    file_name: str
    flatten: bool | None = None
    media_type: str


class RedteamJobSummary(BaseModel):
    agent_id: str | None = None
    attacks: int = Field(..., description='Non-control attacks attempted.')
    blocked: int = Field(..., description='Attacks the guard blocked.')
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    environment_id: str
    error: str | None = None
    id: str
    landed: int = Field(..., description='Attacks that got through.')
    profile: str
    status: JobStatus
    target: str
    updated_at: str = Field(..., description='RFC 3339 timestamp.')
    workspace_id: str


class RedteamPlanRequest(BaseModel):
    name: str | None = Field(
        None,
        description='Display name for the saved plan. Defaults server-side when absent.',
    )


class RedteamReportShare(BaseModel):
    compare_job_id: str | None = None
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    expires_at: str | None = Field(
        None, description='RFC 3339 timestamp; `null` when the link never expires.'
    )
    job_id: str
    path: str = Field(
        ..., description='Relative path that renders the report (e.g. `/r/{token}`).'
    )
    token: str = Field(
        ..., description='Opaque bearer token; also the last path segment.'
    )


class RedteamRunMode(Enum):
    one_off = 'one_off'
    learning = 'learning'


class RedteamSessionEvent(BaseModel):
    actor: str
    content_text: str | None = None
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    event_id: str
    kind: str
    label: str | None = None
    payload: Any | None = None
    seq: int
    trace_id: str | None = None


class ReportSeverity(Enum):
    critical = 'critical'
    high = 'high'
    medium = 'medium'
    low = 'low'
    info = 'info'


class ResponseMode(Enum):
    regular = 'regular'
    streaming = 'streaming'


class RetentionMode(Enum):
    metadata_only = 'metadata_only'
    redacted_body = 'redacted_body'
    full_body = 'full_body'


class ReversalCapability(Enum):
    none = 'none'
    cancel_before_capture = 'cancel_before_capture'
    cancel_pending_refund = 'cancel_pending_refund'
    provider_reversal = 'provider_reversal'
    compensating_charge = 'compensating_charge'
    internal_balance_adjustment = 'internal_balance_adjustment'
    manual_recovery = 'manual_recovery'


class RunEventKind(Enum):
    user_turn = 'user_turn'
    assistant_turn = 'assistant_turn'
    tool_call = 'tool_call'
    workflow_step = 'workflow_step'
    interruption = 'interruption'
    retry = 'retry'
    system_event = 'system_event'
    other = 'other'


class RunEventSummary(BaseModel):
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    id: str
    input_summary: str | None = None
    kind: RunEventKind
    label: str | None = None
    metadata: Any
    occurred_at: str = Field(..., description='RFC 3339 timestamp.')
    output_summary: str | None = None
    run_id: str
    sequence: int
    workspace_id: str


class RunKind(Enum):
    chat_session = 'chat_session'
    live_call = 'live_call'
    workflow = 'workflow'
    job = 'job'
    other = 'other'


class RunStatus(Enum):
    warming = 'warming'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    canceled = 'canceled'


class RunSummary(BaseModel):
    agent_id: str
    blocked_count: int
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    ended_at: str | None = Field(None, description='RFC 3339 timestamp.')
    environment: str
    environment_id: str
    escalated_count: int
    external_id: str | None = None
    id: str
    kind: RunKind
    metadata: Any
    p95_latency_ms: int | None = None
    rewritten_count: int
    started_at: str = Field(..., description='RFC 3339 timestamp.')
    status: RunStatus
    trace_count: int
    updated_at: str = Field(..., description='RFC 3339 timestamp.')
    workspace_id: str


class Severity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class SideEffectClass(Enum):
    none = 'none'
    read = 'read'
    external_communication = 'external_communication'
    file_write = 'file_write'
    shell_exec = 'shell_exec'
    network_call = 'network_call'
    db_mutation = 'db_mutation'
    api_mutation = 'api_mutation'
    memory_write = 'memory_write'
    publish = 'publish'


class SignalEvidence(BaseModel):
    message: str
    provider_id: str
    severity: Severity | None = None


class SpendMeter(Enum):
    actions = 'actions'
    llm_usage = 'llm_usage'


class Tier(Enum):
    deterministic = 'deterministic'
    fuzzy = 'fuzzy'
    llm = 'llm'


class TierStatus(Enum):
    completed = 'completed'
    cancelled = 'cancelled'
    timed_out = 'timed_out'
    skipped = 'skipped'


class Status(Enum):
    resolved = 'resolved'


class Status1(Enum):
    unregistered = 'unregistered'


class ToolResolution2(BaseModel):
    status: Status1


class Status2(Enum):
    resolution_failed = 'resolution_failed'


class ToolResolution3(BaseModel):
    status: Status2


class TraceSummary(BaseModel):
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    decision: str
    domain: str
    elapsed_ms: int
    environment: str
    environment_id: str
    latest_review_outcome: HumanReviewOutcome | None = None
    latest_reviewed_at: str | None = None
    payload: Any
    run_event_id: str | None = None
    run_id: str | None = None
    session_id: str | None = Field(
        None, description='Monitoring session id the trace was tagged with, if any.'
    )
    trace_id: str


class TriggeredPolicy(BaseModel):
    id: str
    reason: str
    severity: Severity


class Trust(Enum):
    trusted = 'trusted'
    untrusted = 'untrusted'
    unknown = 'unknown'


class UpdateBudgetAlertConfigRequest(BaseModel):
    enabled: bool | None = None
    name: str | None = None
    principal_id: str | None = None
    threshold_type: BudgetAlertThresholdType | None = None
    threshold_value: int | None = None
    webhook_url: str | None = None
    window: BudgetAlertWindow | None = None


class UpdateEnforcementProfileRequest(BaseModel):
    display_name: str | None = None
    fail_mode: FailMode | None = None
    fallback_message: str | None = None
    input_action: GatewayInputAction | None = None
    max_regenerations: conint(ge=0) | None = None
    output_action: GatewayOutputAction | None = None
    response_mode: ResponseMode | None = None
    retention_mode: RetentionMode | None = None


class UpdateEnvironmentCheckerModesRequest(BaseModel):
    approval_checker_mode: EnforcementMode | None = None
    flow_checker_mode: EnforcementMode | None = None
    memory_checker_mode: EnforcementMode | None = None
    param_checker_mode: EnforcementMode | None = None


class UpdateGatewayProviderConnectionRequest(BaseModel):
    base_url: str | None = None
    default_model: str | None = None
    display_name: str | None = None
    provider_api_key: str | None = None


class UpdateGatewayRouteRequest(BaseModel):
    agent_id: str | None = None
    display_name: str | None = None
    enforcement_profile_id: str | None = None
    provider_connection_id: str | None = None


class UpdateRunRequest(BaseModel):
    ended_at: str | None = Field(
        None,
        description='RFC 3339 timestamp. Defaults to now when completing/failing/canceling\na run without an explicit timestamp.',
    )
    metadata: Any | None = None
    status: RunStatus | None = None


class UpdateWorkspaceEnvironmentRequest(BaseModel):
    description: str | None = None
    is_default: bool | None = None
    name: str | None = None
    slug: str | None = None


class UpdateWorkspaceSettingsRequest(BaseModel):
    approval_checker_mode: EnforcementMode | None = None
    data_handling_mode: DataHandlingMode | None = None
    default_action: str | None = None
    escalation_webhook_url: str | None = Field(
        None,
        description='Replacement escalation webhook URL. Absent and `null` both mean\n"leave unchanged" — this endpoint cannot clear the URL once set.',
    )
    flow_checker_mode: EnforcementMode | None = None
    memory_checker_mode: EnforcementMode | None = None
    param_checker_mode: EnforcementMode | None = None
    retention_days: str | None = None
    telemetry_enabled: bool | None = None


class UpsertLlmModelPriceRequest(BaseModel):
    input_per_million_minor: int = Field(
        ..., description='USD minor units per 1M prompt tokens.'
    )
    output_per_million_minor: int = Field(
        ..., description='USD minor units per 1M completion tokens.'
    )


class Verdict(Enum):
    allow = 'allow'
    block = 'block'
    rewrite = 'rewrite'
    escalate = 'escalate'


class VerifyResult(BaseModel):
    blocked_landed: conint(ge=0) = Field(
        ...,
        description='Landed cases the candidate now blocks, over the landed cases tested.',
    )
    blocked_variants: conint(ge=0) = Field(
        ...,
        description='Obfuscated/paraphrased variants the candidate blocks, over those tested.',
    )
    control_total: conint(ge=0)
    false_blocks: conint(ge=0) = Field(
        ...,
        description='Benign control cases the candidate wrongly blocks, over those tested.',
    )
    landed_total: conint(ge=0)
    passed: bool
    variant_total: conint(ge=0)


class WorkflowDefinition(BaseModel):
    definition: Any = Field(
        ..., description='Raw exported workflow JSON, kept verbatim.'
    )
    source: str = Field(..., description='Format discriminator, e.g. `n8n`.')


class WorkflowPath(BaseModel):
    sink_category: str = Field(
        ...,
        description='Coarse sink category, e.g. `http`, `email_send`, `database`, `code_exec`.',
    )
    sink_node: str = Field(..., description='Node name of the dangerous operation.')
    sink_type: str = Field(
        ..., description='Raw node type, e.g. `n8n-nodes-base.httpRequest`.'
    )
    source_category: str = Field(
        ...,
        description='Coarse source category, e.g. `email_read`, `webhook`, `form`, `document`.',
    )
    source_node: str = Field(..., description='Node name of the untrusted entry point.')
    source_type: str = Field(
        ..., description='Raw node type, e.g. `n8n-nodes-base.emailReadImap`.'
    )


class WorkflowRequirement(BaseModel):
    name: str
    required_before: list[str] | None = None
    sensitive_steps: list[str] | None = None


class WorkspaceEnvironment(BaseModel):
    created_at: str
    description: str | None = None
    id: str
    is_default: bool
    name: str
    slug: str
    updated_at: str


class WorkspaceEnvironmentListResponse(BaseModel):
    environments: list[WorkspaceEnvironment]


class WorkspaceRole(Enum):
    owner = 'owner'
    admin = 'admin'
    editor = 'editor'
    viewer = 'viewer'


class WorkspaceSettings(BaseModel):
    approval_checker_mode: EnforcementMode | None = Field(
        None, description='Rollout mode for the approval checker. Default `off`.'
    )
    config: Any
    data_handling_mode: DataHandlingMode | None = None
    default_action: str
    escalation_webhook_url: str | None = None
    flow_checker_mode: EnforcementMode | None = Field(
        None,
        description='Rollout mode for the information-flow checker. Default `off`.',
    )
    memory_checker_mode: EnforcementMode | None = Field(
        None,
        description='Rollout mode for the memory write-time checker. Default `off`.',
    )
    param_checker_mode: EnforcementMode | None = Field(
        None,
        description='Rollout mode for the parameter-source authorization checker.\nDefault `off`.',
    )
    retention_days: str
    telemetry_enabled: bool
    updated_at: str | None = Field(None, description='RFC 3339 timestamp.')


class Action(BaseModel):
    operation: str
    parameters: Any | None = None
    side_effect: SideEffectClass | None = None


class AllowedSource(BaseModel):
    kind: str | None = None
    origin: Origin
    source_id: str | None = None


class AnalyticsCatalogDimension(BaseModel):
    dimension: AnalyticsDimension
    label: str


class AnalyticsCatalogMetric(BaseModel):
    default_chart_type: AnalyticsChartType
    label: str
    metric: AnalyticsMetric


class AnalyticsDashboardWidget(BaseModel):
    chart_type: AnalyticsChartType
    group_by: AnalyticsDimension | None = None
    id: str
    layout: AnalyticsWidgetLayout | None = None
    metric: AnalyticsMetric
    title: str


class AnalyticsFacetCatalogResponse(BaseModel):
    chart_types: list[AnalyticsChartType]
    dimensions: list[AnalyticsCatalogDimension]
    facets: list[AnalyticsFacet]
    metrics: list[AnalyticsCatalogMetric]


class ApiError(BaseModel):
    code: ApiErrorCode
    details: Any | None = Field(
        None,
        description='Opaque structured details (e.g. validation field path).\nDefaults to `null`; servers may add fields without breaking SDKs.',
    )
    message: str
    retriable: bool = Field(
        ...,
        description='Whether the caller may retry the same request without modification.\nSDKs honor `Retry-After` when present in addition to this flag.',
    )


class ApiKeyBatchRevokeResponse(BaseModel):
    api_keys: list[DashboardApiKey]


class ApiKeyListResponse(BaseModel):
    api_keys: list[DashboardApiKey]


class AttackVector(BaseModel):
    goal: str = Field(
        ...,
        description='What the attacker is trying to make the agent do (the objective the\nrunner scores against).',
    )
    injection_payload: str = Field(
        ...,
        description='Concrete seed payload to inject. The private runner strengthens this —\nit is a starting point, not the final attack.',
    )
    source_path: WorkflowPath | None = None
    target_operation: str = Field(
        ...,
        description='The operation the vector aims at: a workflow sink category (e.g.\n`http`, `email_send`) or `chat_reply` for a pure chat agent.',
    )
    technique: str = Field(
        ...,
        description='Technique class, e.g. `indirect_prompt_injection`, `instruction_override`,\n`data_exfiltration`, `tool_misuse`, `scope_violation`.',
    )


class BudgetAlertConfig(BaseModel):
    created_at: str = Field(..., description='RFC 3339 timestamps.')
    enabled: bool
    id: str
    name: str
    principal_id: str | None = Field(
        None,
        description='`null` = any principal; the alert is evaluated per acting\nprincipal.',
    )
    threshold_type: BudgetAlertThresholdType
    threshold_value: int
    updated_at: str
    webhook_url: str | None = Field(
        None,
        description='Delivery target. `null` falls back to the workspace\n`escalation_webhook_url`; with neither set, firings are still\nrecorded but nothing is sent.',
    )
    window: BudgetAlertWindow
    workspace_id: str


class BudgetAlertConfigListResponse(BaseModel):
    configs: list[BudgetAlertConfig]


class CheckerFindingEvidence(BaseModel):
    failure_mode: str | None = None
    harm_class: str | None = None
    reason: str
    recommended_verdict: Verdict | None = None
    risk_source: str | None = None
    rule: str
    source_chain: list[str] | None = None


class CheckerRun(BaseModel):
    checker_id: str
    findings: list[CheckerFindingEvidence] | None = None
    mode: EnforcementMode = Field(
        ..., description='Mode the checker ran under at evaluation time.'
    )


class CreateApiKeyResponse(BaseModel):
    api_key: DashboardApiKey
    plaintext_key: str = Field(
        ..., description='Full bearer key. Returned only once at creation time.'
    )


class CreateEnforcementProfileRequest(BaseModel):
    display_name: str
    fail_mode: FailMode
    fallback_message: str
    id: str | None = None
    input_action: GatewayInputAction
    max_regenerations: conint(ge=0) | None = None
    output_action: GatewayOutputAction
    response_mode: ResponseMode | None = None
    retention_mode: RetentionMode


class CreateGatewayProviderConnectionRequest(BaseModel):
    base_url: str | None = None
    default_model: str | None = Field(
        None,
        description='Required for LLM kinds; unused (may be omitted) for `payment_http`.',
    )
    display_name: str
    id: str | None = None
    kind: GatewayProviderKind
    provider_api_key: str


class CreateHumanReviewEventRequest(BaseModel):
    metadata: Any | None = None
    note: str | None = None
    outcome: HumanReviewOutcome
    reason_codes: list[str] | None = None


class CreateInviteRequest(BaseModel):
    email: str
    role: WorkspaceRole


class CreateKnowledgeSourceRequest(BaseModel):
    file: KnowledgeFileInput | None = None
    kind: DashboardKnowledgeSourceKind
    location: str | None = None
    notes: str | None = None
    title: str


class CreateRunEventRequest(BaseModel):
    input_summary: str | None = None
    kind: RunEventKind
    label: str | None = None
    metadata: Any | None = None
    occurred_at: str | None = Field(
        None, description='RFC 3339 timestamp. Defaults to now when omitted.'
    )
    output_summary: str | None = None
    sequence: int | None = None


class CreateRunRequest(BaseModel):
    agent_id: str
    external_id: str | None = None
    kind: RunKind
    metadata: Any | None = None
    status: RunStatus | None = None


class EnforcementProfile(BaseModel):
    created_at: str
    display_name: str
    fail_mode: FailMode
    fallback_message: str
    id: str
    input_action: GatewayInputAction
    max_regenerations: conint(ge=0)
    output_action: GatewayOutputAction
    response_mode: ResponseMode | None = None
    retention_mode: RetentionMode
    updated_at: str


class EnforcementProfileListResponse(BaseModel):
    enforcement_profiles: list[EnforcementProfile]


class FinancialAction(BaseModel):
    amount: MoneyAmount
    counterparty: CounterpartyRef | None = None
    id: str | None = None
    kind: FinancialActionKind
    mandate: MandateRef | None = None
    memo: str | None = None
    metadata: Any | None = None
    operation: str
    principal_id: str
    rail: FinancialRail


class FinancialActionOutcome(BaseModel):
    action_id: str
    final_loss_amount: MoneyAmount | None = None
    metadata: Any | None = None
    occurred_at: str
    provider_reference: str | None = None
    provider_status: str | None = None
    recovery_status: RecoveryStatus
    reversal_capability: ReversalCapability
    status: FinancialActionOutcomeStatus


class FinancialActionRecord(BaseModel):
    action: FinancialAction
    created_at: str
    evidence: list[EvidenceRef] | None = None
    id: str
    status: FinancialActionStatus
    status_reason: str | None = None
    updated_at: str
    workspace_id: str


class FinancialApprovalRequest(BaseModel):
    action_id: str
    approver_roles: list[str] | None = None
    created_at: str
    decided_at: str | None = None
    decided_by: str | None = None
    expires_at: str | None = None
    id: str
    metadata: Any | None = None
    reason: str
    status: FinancialApprovalRequestStatus
    updated_at: str
    workspace_id: str


class FinancialApprovalRequestListResponse(BaseModel):
    approval_requests: list[FinancialApprovalRequest]


class FinancialDecisionRisk(BaseModel):
    code: FinancialDecisionRiskCode
    policy_id: str | None = None
    reason: str
    severity: Severity
    source: str


class FinancialExecutionProof(BaseModel):
    ledger_event_ids: list[str] | None = None
    receipt_id: str | None = None
    status: FinancialExecutionProofStatus


class FinancialMandate(BaseModel):
    created_at: str
    expires_at: str | None = None
    id: str
    metadata: Any | None = None
    principal_id: str
    scope: Any | None = None
    starts_at: str | None = None
    status: FinancialMandateStatus
    updated_at: str
    version: int
    workspace_id: str


class FinancialMandateListResponse(BaseModel):
    mandates: list[FinancialMandate]


class FinancialOutcomeListResponse(BaseModel):
    outcomes: list[FinancialActionOutcome]


class FinancialPolicySelector(BaseModel):
    action_kinds: list[FinancialActionKind] | None = None
    agents: list[str] | None = None
    currencies: list[str] | None = None
    operations: list[str] | None = None
    rails: list[FinancialRail] | None = None


class GatewayProviderConnection(BaseModel):
    base_url: str | None = None
    created_at: str
    credential_status: GatewayCredentialStatus
    default_model: str
    display_name: str
    id: str
    kind: GatewayProviderKind
    updated_at: str


class GatewayProviderConnectionListResponse(BaseModel):
    provider_connections: list[GatewayProviderConnection]


class HardenRejection(BaseModel):
    evidence_seqs: list[int]
    message: str
    reason: HardenRejectionReason
    substrate: str
    verify: VerifyResult | None = None


class HumanReviewAnalyticsResponse(BaseModel):
    by_agent: list[HumanReviewGroupRow]
    by_policy: list[HumanReviewPolicyRow]
    by_run_kind: list[HumanReviewGroupRow]
    by_workflow_step: list[HumanReviewWorkflowStepRow]
    outcomes: HumanReviewOutcomeCounts
    summary: HumanReviewAnalyticsSummary
    top_reasons: list[HumanReviewReasonRow]


class HumanReviewEvent(BaseModel):
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    id: str
    metadata: Any
    note: str | None = None
    outcome: HumanReviewOutcome
    reason_codes: list[str] | None = None
    reviewer_id: str | None = None
    run_event_id: str | None = None
    run_id: str | None = None
    trace_id: str
    workspace_id: str


class HumanReviewEventListResponse(BaseModel):
    review_events: list[HumanReviewEvent]


class KnowledgeSource(BaseModel):
    description: str | None = None
    kb_id: str
    kind: KnowledgeSourceKind | None = None
    url: str | None = None


class KnowledgeSourceDocument(BaseModel):
    created_at: str = Field(..., description='RFC 3339 timestamp.')
    id: str
    kind: DashboardKnowledgeSourceKind
    last_indexed_at: str | None = Field(None, description='RFC 3339 timestamp.')
    location: str | None = None
    metadata: Any
    status: KnowledgeSourceStatus
    title: str
    updated_at: str = Field(..., description='RFC 3339 timestamp.')


class KnowledgeSourceListResponse(BaseModel):
    knowledge_sources: list[KnowledgeSourceDocument]


class Labels(BaseModel):
    confidentiality: Confidentiality | None = None
    integrity: Integrity | None = None
    trust: Trust | None = None


class LlmModelPrice(BaseModel):
    currency: str
    input_per_million_minor: int = Field(
        ..., description='USD minor units per 1M prompt tokens.'
    )
    model: str = Field(..., description='Normalized model key (trimmed, lowercase).')
    output_per_million_minor: int = Field(
        ..., description='USD minor units per 1M completion tokens.'
    )
    source: LlmPriceSource


class LlmPricingListResponse(BaseModel):
    prices: list[LlmModelPrice]


class MyWorkspace(BaseModel):
    id: str
    name: str
    organization_id: str
    role: WorkspaceRole
    slug: str


class MyWorkspacesResponse(BaseModel):
    workspaces: list[MyWorkspace]


class ParamSpec(BaseModel):
    allowed_sources: list[AllowedSource] | None = None
    limit: ParamLimit | None = None
    path: str
    role: ParamRole


class PolicyDocument(BaseModel):
    description: str | None = None
    enabled: bool
    family: PolicyFamily | None = None
    id: str
    severity: Severity
    source_yaml: str


class PolicyDraft(BaseModel):
    action: PolicyAction
    description: str
    id: str
    match_type: PolicyMatchType
    match_value: str
    rewrite: str | None = None
    severity: Severity


class PolicyDraftResponse(BaseModel):
    draft: PolicyDraft


class PolicySummary(BaseModel):
    action: str | None = None
    description: str | None = None
    enabled: bool
    family: PolicyFamily | None = None
    id: str
    owner_agent_id: str | None = None
    severity: Severity


class PolicyValidateResponse(BaseModel):
    errors: list[PolicyValidationIssue]
    policy_id: str | None = None
    valid: bool


class RedactionInfo(BaseModel):
    context_redacted: bool
    entities: list[RedactedEntity]
    input_redacted: bool
    mode: RedactionMode
    proposed_output_redacted: bool
    status: RedactionStatus


class RedteamAttackSession(BaseModel):
    attack: str
    case_id: str | None = Field(
        None,
        description='Stable case identity for raw-vs-guarded benchmark comparison.',
    )
    error: str | None = None
    events: list[RedteamSessionEvent] | None = None
    goal: str
    kind: str | None = Field(
        None, description='Case kind, e.g. `attack`, `benign`, or `attack_under_task`.'
    )
    landed: bool
    outcome: str = Field(..., description='`landed` | `blocked` | `clean` | `error`.')
    runner_session_id: str | None = None
    seq: int
    session_id: str
    status: str = Field(..., description='`running` | `complete` | `error`.')
    trace_id: str | None = None
    track: str | None = Field(
        None, description='Benchmark/security track, e.g. `private_data_flow`.'
    )
    trial_index: int | None = Field(
        None, description='Trial index for live repeated runs.'
    )


class RedteamDispatchRequest(BaseModel):
    agent_id: str | None = Field(
        None,
        description='Optional registered agent this job is associated with (for history).',
    )
    attack_surface: RedteamAttackSurface | None = Field(
        None,
        description='Target surface to attack. `chat` is the default for backward compatibility.',
    )
    attack_vectors: list[AttackVector] | None = Field(
        None,
        description="Optional tailored attack vectors from the agent's `redteam/plan`. When\npresent, the runner uses these seeds so attacks are specific to this\nagent's exposure.",
    )
    document_template: RedteamDocumentTemplate | None = None
    mode: RedteamRunMode | None = Field(
        None,
        description='`one_off` runs a stateless campaign. `learning` lets the private runner\nuse its orchestration-owned learning memory.',
    )
    profile: str = Field(..., description='`fast` | `full` | `max`.')
    target_url: str = Field(
        ..., description='Loopback agent endpoint to attack (arena adapter contract).'
    )


class RedteamJobDetail(BaseModel):
    job: RedteamJobSummary
    sessions: list[RedteamAttackSession]


class RedteamJobListResponse(BaseModel):
    jobs: list[RedteamJobSummary]


class RedteamPlanResponse(BaseModel):
    agent_id: str = Field(..., description='Agent this plan was derived from.')
    generated_at: str = Field(
        ..., description='RFC 3339 timestamp of when the plan was generated/saved.'
    )
    id: str = Field(..., description='Stable plan id (used to select/delete it).')
    name: str = Field(..., description='Human-facing name.')
    paths: list[WorkflowPath] = Field(
        ...,
        description='Injectable `source → sink` paths the static analyzer found in the\nworkflow. Empty for a pure chat agent. Doubles as the static policy seed.',
    )
    unmapped_node_types: list[str] = Field(
        ...,
        description='Workflow node types the analyzer did not recognise — surfaced (not\nsilently dropped) so coverage gaps are explicit.',
    )
    vectors: list[AttackVector] = Field(
        ...,
        description='The tailored attack vectors. Feed these into a dispatch as seeds.',
    )


class RedteamReportAggregates(BaseModel):
    attacks: int = Field(
        ..., description='Non-control attacks (the success-rate denominator).'
    )
    blocked: int
    clean: int
    errored: int
    landed: int
    risk_level: ReportSeverity = Field(
        ...,
        description='Worst severity among landed findings; `Info` when nothing landed.',
    )
    success_rate: float = Field(
        ...,
        description='`landed / attacks` in `[0, 1]` (0 when there are no non-control attacks).',
    )
    total: int = Field(
        ..., description='Every recorded result, including clean control cases.'
    )


class RedteamReportComparison(BaseModel):
    attacks: list[RedteamComparedAttack]
    baseline: RedteamJobSummary
    baseline_aggregates: RedteamReportAggregates
    compare: RedteamJobSummary
    compare_aggregates: RedteamReportAggregates
    delta_points: float = Field(
        ..., description='Baseline minus compared success rate, in percentage points.'
    )


class RedteamReportFinding(BaseModel):
    attack: str
    category: str = Field(
        ..., description='Human-facing attack category (e.g. `credential_disclosure`).'
    )
    evidence: str | None = Field(
        None,
        description='Short excerpt of the agent reply showing what the attack achieved.\nTruncated; redaction-aware (see the server-side builder).',
    )
    goal: str
    landed: bool
    outcome: str = Field(..., description='`landed` | `blocked` | `clean` | `error`.')
    prompt: str | None = None
    seq: int
    severity: ReportSeverity
    trace_id: str | None = None


class RedteamReportPayload(BaseModel):
    aggregates: RedteamReportAggregates
    comparison: RedteamReportComparison | None = None
    findings: list[RedteamReportFinding]
    generated_at: str = Field(
        ..., description='RFC 3339 timestamp of when this report view was generated.'
    )
    job: RedteamJobSummary


class RunDetail(BaseModel):
    events: list[RunEventSummary]
    run: RunSummary
    traces: list[TraceSummary]


class RunEventListResponse(BaseModel):
    events: list[RunEventSummary]


class RunListResponse(BaseModel):
    runs: list[RunSummary]


class Source(BaseModel):
    id: str
    kind: str | None = None
    labels: Labels | None = None
    origin: Origin


class SourceLabelEvidence(BaseModel):
    basis: LabelBasisSet
    labels: Labels
    source_id: str


class SourceLabelPolicy(BaseModel):
    confidentiality: Confidentiality | None = None
    integrity: Integrity | None = None
    origin: Origin
    trust: Trust | None = None


class SourceLabelPolicyEntry(BaseModel):
    enabled: bool
    policy: SourceLabelPolicy


class SourceLabelPolicyListResponse(BaseModel):
    policies: list[SourceLabelPolicyEntry]


class TierResult(BaseModel):
    elapsed_ms: conint(ge=0)
    reasons: list[TriggeredPolicy] | None = None
    status: TierStatus
    tier: Tier


class ToolMetadata(BaseModel):
    approval: ApprovalRule | None = None
    params: list[ParamSpec] | None = None
    reversible: bool
    sandbox_hint: Any | None = None
    side_effect: SideEffectClass
    tool: str


class ToolMetadataEntry(BaseModel):
    enabled: bool
    metadata: ToolMetadata


class ToolMetadataListResponse(BaseModel):
    tools: list[ToolMetadataEntry]


class ToolResolution1(BaseModel):
    metadata: ToolMetadata
    status: Status


class ToolResolution(RootModel[ToolResolution1 | ToolResolution2 | ToolResolution3]):
    root: ToolResolution1 | ToolResolution2 | ToolResolution3 = Field(
        ...,
        description="Outcome of resolving an event's `action.operation` against the\nworkspace tool-metadata registry. Resolution is evidence; checkers and\npolicies decide whether that evidence changes the decision.",
    )


class TraceListResponse(BaseModel):
    traces: list[TraceSummary]


class UpsertSourceLabelPolicyRequest(SourceLabelPolicy):
    enabled: bool | None = None


class UpsertToolMetadataRequest(ToolMetadata):
    enabled: bool | None = None


class WorkspaceInvite(BaseModel):
    created_at: str = Field(..., description='RFC3339 timestamps.')
    email: str
    expires_at: str
    id: str
    invited_by_user_id: str | None = None
    role: WorkspaceRole
    status: InviteStatus
    workspace_id: str


class WorkspaceMember(BaseModel):
    joined_at: str = Field(..., description='RFC3339 timestamp.')
    role: WorkspaceRole
    user_id: str
    username: str


class AgentProfile(BaseModel):
    agent_id: str
    authority: AgentAuthority
    display_name: str
    escalation_triggers: list[str] | None = None
    knowledge_sources: list[KnowledgeSource] | None = None
    scope: AgentScope
    system_prompt: str | None = Field(
        None,
        description='Raw system prompt the customer ships to their LLM. Source of truth\nfor auto-generating guardrails: `POST /v1/agents/{id}/guardrails:generate`\nreads this and asks an LLM to derive a policy set tailored to it.\nOptional at the type level so existing profiles keep deserializing;\nthe generate endpoint enforces presence at call time.',
    )
    target_url: str | None = Field(
        None,
        description='Loopback endpoint this agent is reachable at (the arena adapter contract),\ncaptured at import so the Attacks page can target it without re-typing.\nLoopback-only; validated at the web edge and by the dispatch SSRF guard.',
    )
    tone: AgentTone
    workflow_definition: WorkflowDefinition | None = None
    workflow_requirements: list[WorkflowRequirement] | None = Field(
        None,
        description='Domain workflows that require checks before sensitive steps are advanced.\nHardening uses these as synthesis context after a red-team attack lands.',
    )


class AnalyticsDashboardViewConfig(BaseModel):
    filters: list[AnalyticsFilter]
    widgets: list[AnalyticsDashboardWidget]


class CreateAnalyticsDashboardViewRequest(BaseModel):
    config: AnalyticsDashboardViewConfig
    is_default: bool | None = None
    name: str


class CreateFinancialActionRequest(BaseModel):
    action: FinancialAction
    evidence: list[EvidenceRef] | None = None
    execute: bool | None = None
    idempotency_key: str


class CreateFinancialPolicyRequest(BaseModel):
    allowed_counterparty_ids: list[str] | None = None
    approval_threshold_minor: int | None = None
    approver_roles: list[str] | None = None
    daily_minor: int | None = None
    denied_counterparty_ids: list[str] | None = None
    description: str | None = None
    failed_precondition_action: PolicyAction | None = None
    hold_above_minor: int | None = None
    hold_new_counterparty: bool | None = None
    id: str
    mandate_required: bool | None = None
    meter: SpendMeter | None = Field(
        None, description='Spend meter this policy governs; omitted means `actions`.'
    )
    missing_evidence_action: PolicyAction | None = None
    monthly_minor: int | None = None
    on_breach: PolicyAction | None = None
    per_transaction_minor: int | None = None
    refund_original_method_only: bool | None = None
    required_preconditions: list[FinancialActionPrecondition] | None = None
    severity: Severity | None = None
    weekly_minor: int | None = None
    when: FinancialPolicySelector | None = Field(
        None,
        description='Selectors choosing which actions/calls the policy applies to.\nOmitted means "match everything on the policy\'s meter" — valid\nfor `llm_usage` budgets; `actions` policies must set at least\none selector (enforced at creation).',
    )


class CreateInviteResponse1(BaseModel):
    kind: Kind
    member: WorkspaceMember


class CreateInviteResponse2(BaseModel):
    invite: WorkspaceInvite
    kind: Kind1


class CreateInviteResponse(RootModel[CreateInviteResponse1 | CreateInviteResponse2]):
    root: CreateInviteResponse1 | CreateInviteResponse2 = Field(
        ...,
        description="POST `/v1/team/invites` outcome. Discriminated by `kind`:\n- `added` — the email matched an existing user; they're now a\n  workspace member. No accept step needed.\n- `invited` — no account exists for that email yet; we recorded\n  a pending membership intent. When the user signs up with this\n  email (any time, anywhere), they're auto-joined on their next\n  page load via the `accept_pending_invites_for_email` path.",
    )


class Decision(BaseModel):
    checked_input_excerpt: str | None = None
    checked_output_excerpt: str | None = None
    constraints: Any | None = None
    failure_mode: str | None = None
    harm_class: str | None = None
    latency_ms: conint(ge=0)
    reason: str
    redaction: RedactionInfo | None = None
    remediation: str | None = None
    risk_source: str | None = None
    safe_output: str | None = None
    source_chain: list[str] | None = None
    tier_results: list[TierResult] | None = Field(
        None,
        description='Per-tier breakdown produced by the parallel-cancel orchestrator.\nEmpty for callers that only ran the synchronous `Engine::check`\npath; populated when `Engine::check_async` is used.',
    )
    trace_id: str
    triggered_policies: list[TriggeredPolicy]
    verdict: Verdict
    violated_rule: str | None = None


class FinancialActionListResponse(BaseModel):
    actions: list[FinancialActionRecord]


class FinancialAuthorizationScopeProof(BaseModel):
    checked: bool
    reason: str | None = None
    result: FinancialEligibilityStatus
    scope_ref: MandateRef | None = None
    scope_snapshot: FinancialMandate | None = None
    source: str | None = None


class FinancialPolicyRecord(BaseModel):
    allowed_counterparty_ids: list[str] | None = None
    approval_threshold_minor: int | None = None
    approver_roles: list[str] | None = None
    daily_minor: int | None = None
    denied_counterparty_ids: list[str] | None = None
    description: str | None = None
    enabled: bool
    failed_precondition_action: PolicyAction
    hold_above_minor: int | None = None
    hold_new_counterparty: bool | None = None
    id: str
    mandate_required: bool | None = None
    meter: SpendMeter | None = Field(
        None, description='Spend meter this policy governs.'
    )
    missing_evidence_action: PolicyAction
    monthly_minor: int | None = None
    on_breach: PolicyAction
    per_transaction_minor: int | None = None
    refund_original_method_only: bool | None = None
    required_preconditions: list[FinancialActionPrecondition] | None = None
    severity: Severity
    weekly_minor: int | None = None
    when: FinancialPolicySelector


class GuardrailGenerateResponse(BaseModel):
    generated: list[PolicyDocument]


class GuardrailListResponse(BaseModel):
    policies: list[PolicySummary]


class HardenCandidate(BaseModel):
    evidence_seqs: list[int] = Field(
        ..., description='`seq` of the landed cases this candidate was derived from.'
    )
    existing_policy_id: str | None = Field(
        None, description='Existing policy id when `operation = tighten`.'
    )
    operation: HardenCandidateOperation = Field(
        ...,
        description='Whether this recommendation creates a new policy or tightens an existing\nstable harden policy id.',
    )
    policy: PolicyDocument = Field(
        ...,
        description='The synthesized policy (persisted `enabled = false` when `persist`).',
    )
    source: str = Field(
        ..., description='Where the match logic came from: `llm` | `deterministic`.'
    )
    substrate: str = Field(
        ...,
        description='Enforcement substrate, e.g. `semantic_output` | `regex_output` |\n`approval` | `param_source`.',
    )
    verify: VerifyResult


class HardenResponse(BaseModel):
    candidates: list[HardenCandidate]
    generated_at: str = Field(
        ..., description='RFC 3339 timestamp of when these candidates were generated.'
    )
    rejections: list[HardenRejection] = Field(
        ..., description='Candidate attempts that were intentionally not recommended.'
    )
    unreachable: list[str] = Field(
        ...,
        description="Substrates a landed attack needed but that this job's traces could not\nreach (e.g. an action attack with only output-level traces). Surfaced\nso coverage gaps are explicit rather than silently approximated.",
    )


class InviteListResponse(BaseModel):
    invites: list[WorkspaceInvite]


class LabelResolution(BaseModel):
    derived: dict[str, Labels] | None = Field(
        None,
        description='Parameter path -> labels derived over provenance. A path absent\nfrom this map has unknown derivation — absence is never "clean".',
    )
    policy_status: LabelPolicyStatus
    sources: list[SourceLabelEvidence] | None = None


class MemberListResponse(BaseModel):
    members: list[WorkspaceMember]


class PolicyBatchSetEnabledResponse(BaseModel):
    policies: list[PolicySummary]


class PolicyListResponse(BaseModel):
    policies: list[PolicySummary]


class RedteamPlanListResponse(BaseModel):
    plans: list[RedteamPlanResponse]


class UpdateAnalyticsDashboardViewRequest(BaseModel):
    config: AnalyticsDashboardViewConfig | None = None
    is_default: bool | None = None
    name: str | None = None


class AgentListResponse(BaseModel):
    agents: list[AgentProfile]


class AnalyticsDashboardView(BaseModel):
    config: AnalyticsDashboardViewConfig
    created_at: str
    id: str
    is_default: bool
    name: str
    updated_at: str


class AnalyticsDashboardViewListResponse(BaseModel):
    views: list[AnalyticsDashboardView]


class FinancialActionDecisionReceipt(BaseModel):
    action_id: str
    amount: MoneyAmount
    approval: ApprovalRequirement | None = None
    authorization_scope: FinancialAuthorizationScopeProof
    counterparty: CounterpartyRef | None = None
    created_at: str
    decision: FinancialActionDecision
    evidence: list[FinancialEvidenceProof] | None = None
    execution: FinancialExecutionProof
    operation: str
    principal_id: str
    reason: str
    risks: list[FinancialDecisionRisk] | None = None
    schema_: str = Field(..., alias='schema')
    status: FinancialActionStatus
    updated_at: str


class FinancialPolicyListResponse(BaseModel):
    policies: list[FinancialPolicyRecord]


class GuardEvent(BaseModel):
    action: Action
    checks: list[CheckerRun] | None = Field(
        None,
        description='Checker evaluation evidence attached by the event pipeline.\nServer-populated: the pipeline resets this before evaluating, so\ncollector-submitted values never survive.',
    )
    context: Any | None = None
    kind: EventKind
    label_resolution: LabelResolution | None = None
    principal: Principal
    provenance: ProvenanceMap | None = None
    resolution: ToolResolution | None = None
    signals: list[SignalEvidence] | None = Field(
        None,
        description='Advisory signal evidence attached by the event pipeline.\nServer-populated: the pipeline resets this before evaluating, so\ncollector-submitted values never survive. Signals never change\nthe decision.',
    )
    sources: list[Source] | None = None
