# Generated by `cargo run -p tl-codegen` from docs/openapi.yaml.
# Do not hand-edit.

# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, conint


class Channel(Enum):
    voice = 'voice'
    chat = 'chat'
    email = 'email'


class CheckRequest(BaseModel):
    agent_id: str
    channel: Channel
    context: Any | None = None
    input: str
    policies: list[str] | None = None
    proposed_output: str
    trace_id: str | None = None


class Severity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class TriggeredPolicy(BaseModel):
    id: str
    reason: str
    severity: Severity


class Verdict(Enum):
    allow = 'allow'
    block = 'block'
    rewrite = 'rewrite'
    escalate = 'escalate'


class Decision(BaseModel):
    latency_ms: conint(ge=0)
    reason: str
    safe_output: str | None = None
    trace_id: str
    triggered_policies: list[TriggeredPolicy]
    verdict: Verdict
