"""TrustLoopGuard Python SDK.

Public surface:
    Client          — HTTP client for GuardEvent runtime submissions
    GuardEvent      — what the agent loop submits
    Decision        — what TrustLoopGuard returns
    Verdict, Channel, Severity, TriggeredPolicy — supporting wire types

Type definitions are generated from the canonical Rust types in `tl-core`
via `cargo run -p tl-codegen`. Do not hand-edit `_generated/`.
"""

from trustloopguard.client import AsyncClient, Client
from trustloopguard.guard import (
    GuardLogEvent,
    GuardMode,
    OutputGuard,
    RegenerateFeedback,
    guard,
    guard_async,
)
from trustloopguard._generated.types import (
    Action,
    AllowedSource,
    ApiError,
    ApiErrorCode,
    ApprovalRule,
    Channel,
    Confidentiality,
    CounterpartyRef,
    CreateFinancialActionRequest,
    CreateFinancialMandateRequest,
    CreateRunEventRequest,
    CreateRunRequest,
    Decision,
    EventKind,
    EvidenceRef,
    FinancialAction,
    FinancialActionListResponse,
    FinancialActionKind,
    FinancialApprovalRequest,
    FinancialApprovalRequestListResponse,
    FinancialApprovalRequestStatus,
    FinancialActionRecord,
    FinancialActionStatus,
    FinancialMandate,
    FinancialMandateListResponse,
    FinancialMandateStatus,
    FinancialReceipt,
    FinancialRail,
    GuardEvent,
    GuardrailGenerateResponse,
    GuardrailListResponse,
    Integrity,
    Labels,
    MandateRef,
    MoneyAmount,
    Origin,
    ParamRole,
    ParamSpec,
    Principal,
    ProvenanceMap,
    RunDetail,
    RunEventKind,
    RunEventListResponse,
    RunEventSummary,
    RunKind,
    RunListResponse,
    RunStatus,
    RunSummary,
    Severity,
    SideEffectClass,
    Source,
    ToolMetadata,
    TraceListResponse,
    TraceSummary,
    TriggeredPolicy,
    Trust,
    UpdateRunRequest,
    Verdict,
)
from trustloopguard.errors import (
    Decode,
    Forbidden,
    Gone,
    Internal,
    Invalid,
    NotFound,
    RateLimited,
    SdkError,
    Transport,
    Unauthorized,
    Unavailable,
    Unprocessable,
)
from trustloopguard.retry import RetryConfig

__all__ = [
    # Client
    "AsyncClient",
    "Client",
    # Wire types
    "Action",
    "AllowedSource",
    "ApiError",
    "ApiErrorCode",
    "ApprovalRule",
    "Channel",
    "Confidentiality",
    "CounterpartyRef",
    "CreateFinancialActionRequest",
    "CreateFinancialMandateRequest",
    "CreateRunEventRequest",
    "CreateRunRequest",
    "Decision",
    "EventKind",
    "EvidenceRef",
    "FinancialAction",
    "FinancialActionListResponse",
    "FinancialActionKind",
    "FinancialApprovalRequest",
    "FinancialApprovalRequestListResponse",
    "FinancialApprovalRequestStatus",
    "FinancialActionRecord",
    "FinancialActionStatus",
    "FinancialMandate",
    "FinancialMandateListResponse",
    "FinancialMandateStatus",
    "FinancialReceipt",
    "FinancialRail",
    "GuardEvent",
    "GuardrailGenerateResponse",
    "GuardrailListResponse",
    "Integrity",
    "Labels",
    "MandateRef",
    "MoneyAmount",
    "Origin",
    "ParamRole",
    "ParamSpec",
    "Principal",
    "ProvenanceMap",
    "RunDetail",
    "RunEventKind",
    "RunEventListResponse",
    "RunEventSummary",
    "RunKind",
    "RunListResponse",
    "RunStatus",
    "RunSummary",
    "Severity",
    "SideEffectClass",
    "Source",
    "ToolMetadata",
    "TraceListResponse",
    "TraceSummary",
    "TriggeredPolicy",
    "Trust",
    "UpdateRunRequest",
    "Verdict",
    # Retry
    "RetryConfig",
    # Errors
    "SdkError",
    "Invalid",
    "Unauthorized",
    "Forbidden",
    "NotFound",
    "Gone",
    "Unprocessable",
    "RateLimited",
    "Internal",
    "Unavailable",
    "Transport",
    "Decode",
    # Guard helper
    "guard",
    "guard_async",
    "GuardLogEvent",
    "GuardMode",
    "OutputGuard",
    "RegenerateFeedback",
]

__version__ = "0.0.1"
