//! Regenerate derived wire artifacts from `tl-core`, `tl-policy`, and
//! `tl-server` (for the OpenAPI doc).
//!
//! Run from the repo root:
//!     cargo run -p tl-codegen
//!     cargo run -p tl-codegen -- --check     # CI mode: fail if drift
//!
//! Outputs:
//!     docs/openapi.yaml
//!     policies/decision.schema.json
//!     policies/guard-event.schema.json
//!     policies/tool-metadata.schema.json
//!     policies/source-label-policy.schema.json
//!     policies/policy.schema.json
//!     docs/contracts/redteam-runner.schema.json
//!     sdks/typescript/src/generated/   (placeholder until ts-rs is wired)

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use clap::Parser;
use schemars::schema_for;
use tl_core::{AgentProfile, AuthorizationDecision, GuardEvent, SourceLabelPolicy, ToolMetadata};
use tl_policy::Policy;
use tl_server::ApiDoc;
use utoipa::OpenApi;

#[derive(Parser)]
struct Args {
    /// Fail with non-zero exit if generated files differ from disk.
    /// Wire this into CI to catch missed regenerations.
    #[arg(long)]
    check: bool,
}

fn repo_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .expect("repo root")
}

fn write_or_check(path: &Path, contents: &str, check: bool) -> Result<()> {
    if check {
        let on_disk =
            fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        if on_disk != contents {
            bail!(
                "drift: {} is out of sync with derived types. Run `cargo run -p tl-codegen` and commit.",
                path.display()
            );
        }
        Ok(())
    } else {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
        println!("wrote {}", path.display());
        Ok(())
    }
}

fn main() -> Result<()> {
    let args = Args::parse();
    let root = repo_root();

    // 1. OpenAPI YAML — sourced from tl-server's annotated handlers.
    let mut openapi = serde_yaml::to_value(ApiDoc::openapi()).context("render openapi")?;
    patch_openapi_label_policy_upsert(&mut openapi);
    let openapi_yaml = serde_yaml::to_string(&openapi).context("serialize openapi")?;
    write_or_check(&root.join("docs/openapi.yaml"), &openapi_yaml, args.check)?;

    // 2. JSON Schemas for each wire type. Consumers: dashboard editor,
    //    request validator, downstream Pydantic generation.
    let schemas = [
        (
            "policies/decision.schema.json",
            schema_for!(AuthorizationDecision),
        ),
        ("policies/guard-event.schema.json", schema_for!(GuardEvent)),
        (
            "policies/tool-metadata.schema.json",
            schema_for!(ToolMetadata),
        ),
        (
            "policies/source-label-policy.schema.json",
            schema_for!(SourceLabelPolicy),
        ),
        ("policies/policy.schema.json", schema_for!(Policy)),
        (
            "policies/agent-profile.schema.json",
            schema_for!(AgentProfile),
        ),
        (
            "docs/contracts/redteam-runner.schema.json",
            schema_for!(tl_core::redteam_runner::RedteamRunnerContract),
        ),
    ];
    for (rel, schema) in schemas {
        let json = serde_json::to_string_pretty(&schema)? + "\n";
        write_or_check(&root.join(rel), &json, args.check)?;
    }

    // 3. TypeScript types via ts-rs. ts-rs writes files when its generated
    //    `export_bindings_*` test functions run; we invoke them here as a
    //    child process. TS_RS_EXPORT_DIR points the writer at the SDK dir.
    let ts_dir = root.join("sdks/typescript/src/generated");
    let ts_export = tempfile::tempdir()?;

    let status = std::process::Command::new(env!("CARGO"))
        .args([
            "test",
            "-p",
            "tl-core",
            "--features",
            "ts-export",
            "--",
            "export_bindings",
        ])
        .env("TS_RS_EXPORT_DIR", ts_export.path())
        .current_dir(&root)
        .status()
        .context("run ts-rs export via cargo test")?;
    if !status.success() {
        bail!("ts-rs export failed; check `cargo test -p tl-core --features ts-export`");
    }
    normalize_typescript(ts_export.path())?;
    sync_typescript_bindings(ts_export.path(), &ts_dir, args.check)?;

    let readme_path = ts_dir.join("README.md");
    let readme = "Generated by `cargo run -p tl-codegen`. Do not edit by hand.\n";
    write_or_check(&readme_path, readme, args.check)?;

    // 4. Pydantic v2 models from the OpenAPI spec via datamodel-code-generator.
    //    The OpenAPI YAML was just written above, so its components match
    //    the canonical Rust types. Skipped (with a warning) if the tool is
    //    not installed locally; CI must have it installed.
    //
    //    datamodel-code-generator releases disagree on how `anyOf`
    //    constraint blocks affect generated models (CI installs the
    //    latest), so Python renders from a copy with the label-policy
    //    upsert constraint stripped. The invariant stays in
    //    docs/openapi.yaml for OpenAPI clients and is enforced
    //    server-side (422) regardless.
    let py_out = root.join("sdks/python/src/featherlane_ai/_generated/types.py");
    let mut python_spec = openapi.clone();
    strip_label_policy_upsert_constraint(&mut python_spec);
    // datamodel-codegen embeds the input file name in its generated
    // header, so the copy must keep the canonical `openapi.yaml` name
    // (inside a temp dir) or every run drifts.
    let python_spec_dir = tempfile::tempdir()?;
    let python_spec_path = python_spec_dir.path().join("openapi.yaml");
    fs::write(
        &python_spec_path,
        serde_yaml::to_string(&python_spec).context("serialize python spec")?,
    )?;
    if let Some(rendered) = render_pydantic(&python_spec_path)? {
        write_or_check(&py_out, &rendered, args.check)?;
    } else if args.check {
        bail!(
            "datamodel-codegen not installed but --check was requested. \
             Install with: pip install datamodel-code-generator"
        );
    } else {
        eprintln!(
            "warning: datamodel-codegen not installed; skipping Python type generation. \
             Install with: pip install datamodel-code-generator"
        );
    }

    println!(
        "{}",
        if args.check {
            "ok: artifacts in sync"
        } else {
            "ok: artifacts regenerated"
        }
    );
    Ok(())
}

/// The server rejects upserts where no label family is set (422); encode
/// that invariant in the schema so generated clients cannot construct a
/// guaranteed-fail payload.
fn patch_openapi_label_policy_upsert(openapi: &mut serde_yaml::Value) {
    let Some(upsert) = openapi
        .get_mut("components")
        .and_then(|components| components.get_mut("schemas"))
        .and_then(|schemas| schemas.get_mut("UpsertSourceLabelPolicyRequest"))
    else {
        return;
    };

    upsert["anyOf"] = serde_yaml::to_value(serde_json::json!([
        { "required": ["trust"] },
        { "required": ["confidentiality"] },
        { "required": ["integrity"] }
    ]))
    .expect("label policy constraint serialize");
}

/// Inverse of `patch_openapi_label_policy_upsert`, applied to the copy of
/// the spec fed to datamodel-code-generator (see the Python step in
/// `main` for why).
fn strip_label_policy_upsert_constraint(openapi: &mut serde_yaml::Value) {
    let Some(upsert) = openapi
        .get_mut("components")
        .and_then(|components| components.get_mut("schemas"))
        .and_then(|schemas| schemas.get_mut("UpsertSourceLabelPolicyRequest"))
        .and_then(serde_yaml::Value::as_mapping_mut)
    else {
        return;
    };
    upsert.remove(serde_yaml::Value::String("anyOf".into()));
}

fn normalize_typescript(dir: &Path) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().and_then(|value| value.to_str()) != Some("ts") {
            continue;
        }
        let body = fs::read_to_string(&path)?;
        let normalized = body
            .lines()
            .map(|line| normalize_typescript_line(line.trim_end()))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n";
        if normalized != body {
            fs::write(&path, normalized)?;
        }
    }
    Ok(())
}

fn normalize_typescript_line(line: &str) -> String {
    let Some(from_index) = line.find("from ") else {
        return line.to_string();
    };
    let quote_index = from_index + "from ".len();
    let Some(quote) = line[quote_index..].chars().next() else {
        return line.to_string();
    };
    if quote != '\'' && quote != '"' {
        return line.to_string();
    }

    let specifier_start = quote_index + quote.len_utf8();
    let Some(specifier_end_offset) = line[specifier_start..].find(quote) else {
        return line.to_string();
    };
    let specifier_end = specifier_start + specifier_end_offset;
    let specifier = &line[specifier_start..specifier_end];
    if !(specifier.starts_with("./") || specifier.starts_with("../"))
        || Path::new(specifier).extension().is_some()
    {
        return line.to_string();
    }

    format!(
        "{}{}.js{}",
        &line[..specifier_start],
        specifier,
        &line[specifier_end..]
    )
}

fn sync_typescript_bindings(source: &Path, target: &Path, check: bool) -> Result<()> {
    fs::create_dir_all(target)?;
    let mut expected = Vec::new();
    for entry in fs::read_dir(source)? {
        let path = entry?.path();
        if path.extension().and_then(|value| value.to_str()) != Some("ts") {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|value| value.to_str())
            .context("generated TypeScript file name")?
            .to_string();
        expected.push(name.clone());
        let contents = fs::read_to_string(&path)?;
        write_or_check(&target.join(name), &contents, check)?;
    }
    expected.sort();

    let mut actual = fs::read_dir(target)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("ts"))
        .filter_map(|path| path.file_name()?.to_str().map(str::to_string))
        .collect::<Vec<_>>();
    actual.sort();
    let stale = actual
        .iter()
        .filter(|name| expected.binary_search(name).is_err())
        .cloned()
        .collect::<Vec<_>>();
    if check && !stale.is_empty() {
        bail!(
            "stale generated TypeScript files in {}: {}",
            target.display(),
            stale.join(", ")
        );
    }
    if !check {
        for name in stale {
            fs::remove_file(target.join(name))?;
        }
    }
    Ok(())
}

/// Run `datamodel-codegen` against the freshly written OpenAPI YAML and
/// return the generated Python source as a string. Returns `Ok(None)` if
/// the tool isn't on PATH so callers can decide whether to warn or fail.
fn render_pydantic(openapi_path: &Path) -> Result<Option<String>> {
    let tmp = tempfile::Builder::new().suffix(".py").tempfile()?;
    let output = std::process::Command::new("datamodel-codegen")
        .args([
            "--input",
            openapi_path.to_str().unwrap(),
            "--input-file-type",
            "openapi",
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--use-standard-collections",
            "--use-union-operator",
            // Without this every run produces a fresh timestamp, breaking
            // the --check drift gate.
            "--disable-timestamp",
            "--output",
            tmp.path().to_str().unwrap(),
        ])
        .output();
    match output {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e.into()),
        Ok(out) if !out.status.success() => bail!(
            "datamodel-codegen failed:\n{}",
            String::from_utf8_lossy(&out.stderr)
        ),
        Ok(_) => {
            let body = fs::read_to_string(tmp.path())?;
            let header = "# Generated by `cargo run -p tl-codegen` from docs/openapi.yaml.\n\
                          # Do not hand-edit.\n\n";
            Ok(Some(format!("{header}{body}")))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::normalize_typescript_line;

    #[test]
    fn adds_javascript_extension_to_generated_relative_imports() {
        assert_eq!(
            normalize_typescript_line(r#"import type { Action } from "./Action";"#),
            r#"import type { Action } from "./Action.js";"#
        );
    }

    #[test]
    fn preserves_package_and_explicit_extension_imports() {
        assert_eq!(
            normalize_typescript_line(r#"import type { Action } from "@scope/types";"#),
            r#"import type { Action } from "@scope/types";"#
        );
        assert_eq!(
            normalize_typescript_line(r#"import type { Action } from "./Action.js";"#),
            r#"import type { Action } from "./Action.js";"#
        );
    }
}
